// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYw5K823k1RKh9Ep_3xKwmCp9hBtS7gCI',
    appId: '1:722142519564:web:20c6b9833b6ee572906929',
    messagingSenderId: '722142519564',
    projectId: 'flutter-shopping-app-4111c',
    authDomain: 'flutter-shopping-app-4111c.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-4111c.firebasestorage.app',
    measurementId: 'G-RX5KVMWDJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrjItl2ZYoQ5-roFKOHS4p9wXliPQIS8M',
    appId: '1:722142519564:android:e6151464a69799e1906929',
    messagingSenderId: '722142519564',
    projectId: 'flutter-shopping-app-4111c',
    storageBucket: 'flutter-shopping-app-4111c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuXYn7jktdPxmmLv1qUr2ED6MuFQTmBc8',
    appId: '1:722142519564:ios:bcf06d55d54205a1906929',
    messagingSenderId: '722142519564',
    projectId: 'flutter-shopping-app-4111c',
    storageBucket: 'flutter-shopping-app-4111c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuXYn7jktdPxmmLv1qUr2ED6MuFQTmBc8',
    appId: '1:722142519564:ios:bcf06d55d54205a1906929',
    messagingSenderId: '722142519564',
    projectId: 'flutter-shopping-app-4111c',
    storageBucket: 'flutter-shopping-app-4111c.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYw5K823k1RKh9Ep_3xKwmCp9hBtS7gCI',
    appId: '1:722142519564:web:81fb22ed072e2e93906929',
    messagingSenderId: '722142519564',
    projectId: 'flutter-shopping-app-4111c',
    authDomain: 'flutter-shopping-app-4111c.firebaseapp.com',
    storageBucket: 'flutter-shopping-app-4111c.firebasestorage.app',
    measurementId: 'G-0JF8LDW2JL',
  );
}
